import { Listing } from "@/lib/api";

export const DEMO_LISTINGS: Listing[] = [
  {
    id: "demo-1",
    source: "homes",
    source_url: "https://www.homes.co.jp/chintai/room/ea5b82044b28d7e4f6f95930e49a0b716ae9bf60/",
    title: "プラムガーデン",
    building_name: "プラムガーデン",
    rent: 100000,
    management_fee: 3000,
    deposit: 100000,
    key_money: 100000,
    address: "東京都杉並区",
    ward: "suginami",
    nearest_station: "新高円寺駅",
    walk_minutes: 5,
    floor_plan: "1LDK",
    size_m2: 30,
    floor: null,
    total_floors: null,
    building_age_years: null,
    built_year: null,
    building_type: "マンション",
    motorcycle_parking: "available",
    bicycle_parking: "available",
    car_parking: "none",
    foreigner_ok: true,
    earthquake_standard: "new",
    features: ["バイク置き場", "駐輪場", "外国人相談可", "新耐震基準"],
    image_url: null,
    scraped_at: "2026-04-01T00:00:00Z",
  },
  {
    id: "demo-2",
    source: "homes",
    source_url: "https://www.homes.co.jp/chintai/room/1658ec076eb2f71203bdac0ffaa71ccfa7375e67/",
    title: "三井マンション",
    building_name: "三井マンション",
    rent: 92000,
    management_fee: 0,
    deposit: 92000,
    key_money: 0,
    address: "東京都杉並区",
    ward: "suginami",
    nearest_station: "新高円寺駅",
    walk_minutes: 9,
    floor_plan: "1LDK",
    size_m2: 33,
    floor: null,
    total_floors: null,
    building_age_years: null,
    built_year: null,
    building_type: "マンション",
    motorcycle_parking: "unknown",
    bicycle_parking: "available",
    car_parking: "unknown",
    foreigner_ok: null,
    earthquake_standard: "old",
    features: ["駐輪場", "旧耐震基準"],
    image_url: null,
    scraped_at: "2026-04-01T00:00:00Z",
  },
  {
    id: "demo-3",
    source: "homes",
    source_url: "https://www.homes.co.jp/chintai/b-31035960093672/",
    title: "エクセレンスハイツ",
    building_name: "エクセレンスハイツ",
    rent: 94000,
    management_fee: 1000,
    deposit: 94000,
    key_money: 94000,
    address: "東京都杉並区",
    ward: "suginami",
    nearest_station: "高円寺駅",
    walk_minutes: 10,
    floor_plan: "1LDK",
    size_m2: 30,
    floor: null,
    total_floors: null,
    building_age_years: null,
    built_year: null,
    building_type: "マンション",
    motorcycle_parking: "available",
    bicycle_parking: "available",
    car_parking: "available",
    foreigner_ok: false,
    earthquake_standard: "new",
    features: ["バイク置き場", "駐輪場", "駐車場", "新耐震基準"],
    image_url: null,
    scraped_at: "2026-04-01T00:00:00Z",
  },
  {
    id: "demo-4",
    source: "homes",
    source_url: "https://www.homes.co.jp/chintai/b-1092810076883/",
    title: "東交ビル",
    building_name: "東交ビル",
    rent: 112000,
    management_fee: 3000,
    deposit: 112000,
    key_money: 112000,
    address: "東京都杉並区",
    ward: "suginami",
    nearest_station: "新高円寺駅",
    walk_minutes: 3,
    floor_plan: "1LDK",
    size_m2: 48,
    floor: null,
    total_floors: null,
    building_age_years: null,
    built_year: null,
    building_type: "ビル",
    motorcycle_parking: "none",
    bicycle_parking: "none",
    car_parking: "none",
    foreigner_ok: null,
    earthquake_standard: "old",
    features: ["旧耐震基準"],
    image_url: null,
    scraped_at: "2026-04-01T00:00:00Z",
  },
  {
    id: "demo-5",
    source: "homes",
    source_url: "https://www.homes.co.jp/chintai/room/b953dff2d373750fd31689dfcbfcb9bbe78e2d3d/",
    title: "B・キャッスル十条",
    building_name: "B・キャッスル十条",
    rent: 105000,
    management_fee: 4000,
    deposit: 105000,
    key_money: 105000,
    address: "東京都北区",
    ward: "kita",
    nearest_station: "東十条駅 / 十条駅",
    walk_minutes: 7,
    floor_plan: "1LDK",
    size_m2: 52,
    floor: null,
    total_floors: null,
    building_age_years: 14,
    built_year: 2012,
    building_type: "マンション",
    motorcycle_parking: "available",
    bicycle_parking: "available",
    car_parking: "unknown",
    foreigner_ok: true,
    earthquake_standard: "new",
    features: ["バイク置き場", "駐輪場", "外国人相談可", "新耐震基準", "dual-station"],
    image_url: null,
    scraped_at: "2026-04-01T00:00:00Z",
  },
];
